#!/bin/bash
# Determine working directory
POPUP=`dirname "$0"`/cocoaDialog.app/Contents/MacOS/cocoaDialog
# Original Agent.cfg OSX default path
CONFDIR_PATH=/Library/Preferences/fusioninventory
  
# Options for cocoaDialog
RUNMODE="inputbox"
TITLE="Local Folder Path"
TEXT="/tmp/fusioninventory"
OTHEROPTS="--float --string-output --resize"
ICON="finder"

#Do the dialog, get the result and strip the Ok button code
RESPONSE=`$POPUP $RUNMODE --button1 "Ok" --button2 "Cancel" $OTHEROPTS  --icon $ICON --title "${TITLE}" --text "${TEXT}"`
RESPONSE=`echo $RESPONSE | sed 's/Ok//g'`

#Add server configuration
echo "#########################" >> $CONFDIR_PATH/agent.cfg
echo "## Local configuration ##" >> $CONFDIR_PATH/agent.cfg
echo "#########################" >> $CONFDIR_PATH/agent.cfg
echo "local = $RESPONSE" >> $CONFDIR_PATH/agent.cfg

