#!/bin/bash
# Determine working directory
POPUP=`dirname "$0"`/cocoaDialog.app/Contents/MacOS/cocoaDialog
# Original Agent.cfg OSX default path
CONFDIR_PATH=/Library/Preferences/fusioninventory
  
# Options for cocoaDialog
RUNMODE="inputbox"
TITLE="Server adress"
TEXT="http://glpiserver/glpi/plugins/fusioninventory/"
OTHEROPTS="--float --string-output --no-cancel"
ICON="network"

#Do the dialog, get the result and strip the Ok button code
RESPONSE=`$POPUP $RUNMODE --button1 "Ok" $OTHEROPTS  --icon $ICON --title "${TITLE}" --text "${TEXT}"`
RESPONSE=`echo $RESPONSE | sed 's/Ok//g'`

#Add server configuration
echo "##########################" >> $CONFDIR_PATH/agent.cfg
echo "## Server Configuration ##" >> $CONFDIR_PATH/agent.cfg
echo "##########################" >> $CONFDIR_PATH/agent.cfg
echo "server = $RESPONSE" >> $CONFDIR_PATH/agent.cfg

