#!/bin/bash
POPUP=`dirname "$0"`/cocoaDialog.app/Contents/MacOS/cocoaDialog
dialog=$($POPUP checkbox --title "Configure options" \
      --label "Choose in this list :" \
      --icon preferences \
      --items `#box0` "TAG" `#box1` "Server Adress" `#box2` "Local folder" \
      --rows 10 \
      --checked 0 1 \
      --value-required \
      --button1 "Ok" \
      --resize);

checkboxes=($(echo "${dialog}" | awk 'NR>1{print $0}'));

if [ "${checkboxes[0]}" = "1" ]; then
. askTAG
fi
if [ "${checkboxes[1]}" = "1" ]; then
. askServer	
fi
if [ "${checkboxes[2]}" = "1" ]; then
. askLocal
fi
exit 0